version: '3.5'
services:
  api1: &api
    build: .
    container_name: api1
    environment:
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '150MB'

  api2:
    <<: *api
    container_name: api2
    ports:
      - "3002:3000"

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha_crystal
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'rinha_crystal']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '50MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
